swagger: "2.0"
info:
  version: 0.0.1
  title: KLD REST API
basePath: /
paths:
  /v1/newaddr:
    get:
      description: Generates new on-chain address for receiving funds
      operationId: newaddr
      security:
        - MacaroonAuth: []
      parameters:
        - in: query
          name: addrType
          description: Address type (bech32)
          type: string
          default: bech32
      responses:
        "200":
          description: Address generated successfully
          schema:
            type: object
            properties:
              address:
                type: string
                description: address
            required:
              - address
        "400":
          description: Bad request
        "500":
          description: Server error
  /v1/peer/connect:
    post:
      description: Connect with a network peer
      operationId: connect
      security:
        - MacaroonAuth: []
      parameters:
        - in: body
          name: body
          required: true
          description: Pubkey@address of the peer
          schema:
            required:
              - id
            type: object
            properties:
              id:
                type: string
      responses:
        "201":
          description: Peer connected successfully
          schema:
            required:
              - id
            type: object
            properties:
              id:
                type: string
                description: Pubkey of connected peer
        "400":
          description: Bad request
        "500":
          description: Server error
  /v1/estimateChannelLiquidity:
    get:
      description: Estimate channel liquidity
      operationId: estimateChannelLiquidity
      security:
        - MacaroonAuth: []
      parameters:
        - in: body
          name: body
          required: true
          schema:
            required:
              - scid
              - target
            type: object
            properties:
              scid:
                type: integer
              target:
                type: string
      responses:
        "200":
          schema:
            required:
              - minimum
              - maximum
            type: object
            properties:
              minimum:
                type: integer
              maximum:
                type: integer
        "400":
          description: Bad request
        "500":
          description: Server error
  /v1/getFees:
    get:
      tags:
        - General Information
      description: Gets the routing fee collected by the node
      operationId: getfees
      security:
        - MacaroonAuth: []
      responses:
        "200":
          description: Routing fee returned successfully
          schema:
            type: object
            properties:
              feeCollected:
                type: integer
                minimum: 0
                description: feeCollected
            required:
              - feeCollected
        "400":
          description: Bad request
        "500":
          description: Server error
  /v1/channel/localremotebal:
    get:
      tags:
        - Channel Management
      description: Fetches the aggregate local and remote channel balance on the node (msat)
      operationId: localremotebal
      security:
        - MacaroonAuth: []
      responses:
        "200":
          description: Local-Remote balance returned successfully
          schema:
            type: object
            properties:
              localBalance:
                type: integer
                minimum: 0
                description: localBalance
              remoteBalance:
                type: integer
                minimum: 0
                description: remoteBalance
              pendingBalance:
                type: integer
                minimum: 0
                description: pendingBalance
              inactiveBalance:
                type: integer
                minimum: 0
                description: inactiveBalance
            required:
              - localBalance
              - remoteBalance
              - pendingBalance
              - inactiveBalance
        "400":
          description: Bad request
        "500":
          description: Server error
  /v1/channel/listPeerChannels:
    get:
      tags:
        - Channel Management
      description: Returns data on channels that are known to the node
      operationId: listpeerchannel
      security:
        - MacaroonAuth: []
      responses:
        "200":
          description: An array of channels is returned
          schema:
            type: object
            properties:
              peer_id:
                type: string
                description: Pub key
              peer_connected:
                type: boolean
                description: Peer connection status (true or false)
              opener:
                type: string
                enum: [local, remote]
                description: Who initiated the channel (local or remote)
              short_channel_id:
                type: string
                description: Short Channel ID
              channel_id:
                type: string
                description: Channel ID
              funding_txid:
                type: string
                description: Channel funding transaction
              private:
                type: boolean
                description: Private channel flag (true or false)
              to_us_msat:
                type: integer
                description: Msatoshis to us
              to_them_msat:
                type: integer
                description: Msatoshis to them
              total_msat:
                type: integer
                description: Msatoshis total
              their_reserve_msat:
                type: integer
                description: Their channel reserve Msats
              our_reserve_msat:
                type: integer
                description: Our channel reserve Msats
              spendable_msat:
                type: integer
                description: Spendable Msats
              receivable_msat:
                type: integer
                description: Receivable Msats
              funding:
                type: object
                description: Funding
              state:
                type: string
                enum: [CHANNELD_NORMAL, OPENINGD]
                description: Channel connection status
              fee_base_msat:
                type: integer
                description: Base Fee Msats
              fee_proportional_millionths:
                type: integer
                description: Fee Proportion Millionth
              dust_limit_msat:
                type: integer
                description: Dust limit Msats
              htlcs:
                type: array
                items:
                  type: object
                description: List of HTLCs
              features:
                type: array
                items:
                  type: string
                description: Features which apply to this channel
              alias:
                type: string
                description: Alias of the node
              minimum_htlc_in_msat:
                type: integer
                description: Minimum HTLC we can receive on this channel
              max_total_htlc_in_msat:
                type: integer
                description: Maximum total HTLCs we can receive on this channel
              minimum_htlc_out_msat:
                type: integer
                description: Mimimum HTLC we can send
              maximum_htlc_out_msat:
                type: integer
                description: Maximum HTLC we can send
            required:
              - peer_id
              - peer_connected
              - opener
              - channel_id
              - private
              - to_us_msat
              - to_them_msat
              - total_msat
              - their_reserve_msat
              - spendable_msat
              - receivable_msat
              - state
              - fee_base_msat
              - fee_proportional_millionths
              - dust_limit_msat
              - features
              - alias
              - maximum_htlc_out_msat
              - minimum_htlc_out_msat
        "400":
          description: Bad request
        "500":
          description: Server error
  /v1/channel/listForwards:
    get:
      tags:
        - Channel Management
      description: Fetch the list of the forwarded htlcs
      operationId: listforwards
      security:
        - MacaroonAuth: []
      parameters:
        - in: query
          name: status
          description: status of the HTLC
          enum: [offered, settled, local_failed, failed]
          type: string
      responses:
        "200":
          description: List of forwarded htlcs are returned per the params specified
          schema:
            type: array
            items:
              type: object
              properties:
                in_channel:
                  type: string
                  description: in_channel
                in_msat:
                  type: integer
                  description: in_msat
                status:
                  type: string
                  description: status of the HTLC
                  enum: [offered, settled, local_failed, failed]
                received_time:
                  type: integer
                  description: the UNIX timestamp when this was received
                out_channel:
                  type: string
                  description: the channel that the HTLC was forwarded to
                payment_hash:
                  type: string
                  description: payment hash sought by HTLC (always 64 characters)
                fee_msat:
                  type: integer
                  description: If out_channel is present, the amount this paid in fees
                out_msat:
                  type: integer
                  description: If out_channel is present, the amount we sent out the out_channel
                resolved_time:
                  type: integer
                  description: If status is "settled" or "failed", the UNIX timestamp when this was resolved
                failcode:
                  type: string
                  description: If status is "local_failed" or "failed", the numeric onion code returned
                failreason:
                  type: string
                  description: If status is "local_failed" or "failed", the name of the onion code returned
              required:
                - in_channel
                - status
                - received_time
        "400":
          description: Bad request
        "500":
          description: Server error
  /v1/channel/history:
    get:
      tags:
        - Channel Management
      description: Fetch our channel history
      operationId: channelhistory
      security:
        - MacaroonAuth: []
      responses:
        "200":
          description: Channel history success
          schema:
            type: array
            items:
              type: object
              properties:
                id:
                  type: string
                  description: channel ID
                scid:
                  type: integer
                  description: short channel ID
                user_channel_id:
                  type: integer
                  description: user channel ID
                counterparty:
                  type: string
                  description: counterparty public key
                funding_txo:
                  type: string
                  description: funding transaction output
                is_public:
                  type: boolean
                  description: is channel public or private
                is_outbound:
                  type: boolean
                  description: is channel inbound or outbound
                value:
                  type: integer
                  description: channel amount in sats
                open_timestamp:
                  type: integer
                  description: time that the channel was opened
                close_timestamp:
                  type: integer
                  description: time that the channel was closed
                closure_reason:
                  type: string
                  description: reason the channel was closed
              required:
                - id
                - scid
                - user_channel_id
                - counterparty
                - funding_txo
                - is_public
                - is_outbound
                - value
                - open_timestamp
                - close_timestamp
                - closure_reason
        "400":
          description: Bad request
        "500":
          description: Server error
  /v1/pay/listPayments:
    get:
      tags:
        - Payments
      description: Returns a detailed list of payments
      operationId: listpayments
      security:
        - MacaroonAuth: []
      parameters:
        - in: query
          name: invoice
          description: BOLT11 invoice
          type: string
      responses:
        "200":
          description: An array of payments objects is returned
          schema:
            type: object
            properties:
              payments:
                type: array
                description: List of payments
                items:
                  type: object
                  properties:
                    id:
                      type: string
                      description: id
                    payment_hash:
                      type: string
                      description: payment_hash
                    destination:
                      type: string
                      description: destination
                    amount_msat:
                      type: number
                      description: amount_msat
                    amount_sent_msat:
                      type: number
                      description: amount_sent_msat
                    created_at:
                      type: integer
                      description: created_at
                    status:
                      type: string
                      description: status
                    payment_preimage:
                      type: string
                      description: payment_preimage
                    bolt11:
                      type: string
                      description: bolt11
                    memo:
                      type: string
                      description: memo
                  required:
                    - id
                    - payment_hash
                    - amount_sent_msat
                    - created_at
                    - status
            required:
              - payments
        "400":
          description: Bad request
        "500":
          description: Server error
