CREATE USER IF NOT EXISTS klnd;

GRANT SELECT ON TABLE * TO klnd;
GRANT INSERT ON TABLE * TO klnd;
GRANT UPDATE ON TABLE * TO klnd;
GRANT DELETE ON TABLE * TO klnd;

CREATE USER IF NOT EXISTS grafana;

