[package]
name = "kld-ctl"
version = "0.1.0"
edition = "2021"
description = "A general node controller for lightning knd"

[workspace]

[dependencies]
anyhow = "1.0.72"
clap = { version = "4.3.12", features = ["derive"] }
serde = "1.0"
serde_derive = "1.0.174"
toml = "0.7.6"
