[package]
name = "kld-ctl"
version = "0.1.0"
edition = "2021"
description = "A general node controller for lightning knd"

[workspace]

[dependencies]
anyhow = "1.0.75"
clap = { version = "4.4.11", features = ["derive"] }
serde = "1.0"
serde_derive = "1.0.188"
toml = "0.8.8"
