[Navigate]
"<esc>"     = "Quit"
"<tab>"     = "SwitchTab"
"<up>"      = "NavUp"
"<down>"    = "NavDown"
"<left>"    = "NavLeft"
"<right>"   = "NavRight"
"<enter>"   = "EnderCmdMode"

[Command]
"<esc>"   = "ExitCmdMode"
"<tab>"   = "SwitchInputs"
"<enter>" = "TriggerExecute"
